-- Bloomora · Alinear tabla english_notes existente con la app
-- Tu esquema actual tiene: user_cedula, title, category, content (jsonb), plain_text, ...
-- La app necesita además: id (PK), content_html, title_font, page_size, etc.
--
-- Ejecutar en Supabase → SQL Editor → Run
-- Luego: Project Settings → API → Reload schema

-- 1) ID autoincremental (obligatorio para la app)
alter table public.english_notes
  add column if not exists id bigint generated by default as identity;

do $$
begin
  if not exists (
    select 1
    from pg_constraint c
    join pg_class t on t.oid = c.conrelid
    join pg_namespace n on n.oid = t.relnamespace
    where n.nspname = 'public'
      and t.relname = 'english_notes'
      and c.contype = 'p'
  ) then
    alter table public.english_notes add primary key (id);
  end if;
exception
  when others then
    raise notice 'PK english_notes: %', sqlerrm;
end $$;

-- 2) Columnas que usa el editor de apuntes
alter table public.english_notes
  add column if not exists title_font text not null default 'popis';

alter table public.english_notes
  add column if not exists title_color text not null default 'black';

alter table public.english_notes
  add column if not exists page_size text not null default 'letter';

alter table public.english_notes
  add column if not exists page_number_enabled boolean not null default false;

alter table public.english_notes
  add column if not exists two_columns boolean not null default false;

alter table public.english_notes
  add column if not exists content_html text not null default '<p><br /></p>';

-- 3) Valores por defecto en columnas que ya tenías
update public.english_notes
set plain_text = coalesce(plain_text, '')
where plain_text is null;

update public.english_notes
set created_at = coalesce(created_at, now())
where created_at is null;

update public.english_notes
set updated_at = coalesce(updated_at, now())
where updated_at is null;

-- 4) Copiar contenido antiguo (jsonb) → content_html si aplica
update public.english_notes
set content_html = case
  when content is null then coalesce(nullif(trim(plain_text), ''), '<p><br /></p>')
  when jsonb_typeof(content) = 'string' then content #>> '{}'
  when content ? 'contentHtml' then content->>'contentHtml'
  when content ? 'html' then content->>'html'
  when content ? 'body' then content->>'body'
  else '<p><br /></p>'
end
where content is not null
  and (content_html is null or content_html = '<p><br /></p>');

-- 5) Restricciones opcionales (como en la migración oficial)
do $$
begin
  alter table public.english_notes
    drop constraint if exists english_notes_page_size_check;
  alter table public.english_notes
    add constraint english_notes_page_size_check
    check (page_size in ('a4', 'letter'));
exception
  when others then
    raise notice 'page_size check: %', sqlerrm;
end $$;

do $$
begin
  alter table public.english_notes
    drop constraint if exists english_notes_title_font_check;
  alter table public.english_notes
    add constraint english_notes_title_font_check
    check (title_font in ('popis', 'arial', 'cursive', 'cursive2'));
exception
  when others then
    raise notice 'title_font check: %', sqlerrm;
end $$;

do $$
begin
  alter table public.english_notes
    drop constraint if exists english_notes_title_color_check;
  alter table public.english_notes
    add constraint english_notes_title_color_check
    check (title_color in ('coral', 'violet', 'babyBlue', 'gray', 'black'));
exception
  when others then
    raise notice 'title_color check: %', sqlerrm;
end $$;

-- 6) FK a profiles (si existe la tabla profiles)
do $$
begin
  if exists (
    select 1 from information_schema.tables
    where table_schema = 'public' and table_name = 'profiles'
  ) then
    alter table public.english_notes
      drop constraint if exists english_notes_user_cedula_fkey;
    alter table public.english_notes
      add constraint english_notes_user_cedula_fkey
      foreign key (user_cedula) references public.profiles(cedula) on delete cascade;
  end if;
end $$;

-- 7) Índices
create index if not exists idx_english_notes_user_cedula
  on public.english_notes(user_cedula);

create index if not exists idx_english_notes_updated_at
  on public.english_notes(user_cedula, updated_at desc);

-- 8) Trigger updated_at (función set_updated_at de Bloomora)
drop trigger if exists trg_english_notes_updated_at on public.english_notes;
create trigger trg_english_notes_updated_at
before update on public.english_notes
for each row
execute function public.set_updated_at();

-- 9) RLS + permisos (modo simple de Bloomora)
alter table public.english_notes enable row level security;

drop policy if exists "english_notes_anon_all" on public.english_notes;
create policy "english_notes_anon_all"
on public.english_notes
for all
using (true)
with check (true);

grant select, insert, update, delete on table public.english_notes to anon, authenticated;

do $$
begin
  grant usage, select on sequence public.english_notes_id_seq to anon, authenticated;
exception
  when undefined_table then
    null;
end $$;

-- 10) Recargar caché PostgREST
notify pgrst, 'reload schema';

-- Opcional: si ya no usarás la columna jsonb "content", puedes borrarla después de verificar:
-- alter table public.english_notes drop column if exists content;
